# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_assignment_proto/features.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gender_classification_pipeline.ml_assignment_proto import user_pb2 as ml__assignment__proto_dot_user__pb2
from gender_classification_pipeline.ml_assignment_proto import recording_device_pb2 as ml__assignment__proto_dot_recording__device__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml_assignment_proto/features.proto',
  package='ml_assignment_proto',
  syntax='proto3',
  serialized_pb=_b('\n\"ml_assignment_proto/features.proto\x12\x13ml_assignment_proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eml_assignment_proto/user.proto\x1a*ml_assignment_proto/recording_device.proto\"&\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\xcf\x01\n\x08\x46\x65\x61tures\x12\'\n\x04user\x18\x01 \x01(\x0b\x32\x19.ml_assignment_proto.User\x12\x36\n\x08recorder\x18\x02 \x01(\x0b\x32$.ml_assignment_proto.RecordingDevice\x12\x32\n\x0erecording_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x08\x66\x65\x61tures\x18\x04 \x03(\x0b\x32\x1c.ml_assignment_proto.Featureb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,ml__assignment__proto_dot_user__pb2.DESCRIPTOR,ml__assignment__proto_dot_recording__device__pb2.DESCRIPTOR,])




_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='ml_assignment_proto.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ml_assignment_proto.Feature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ml_assignment_proto.Feature.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=206,
)


_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='ml_assignment_proto.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='ml_assignment_proto.Features.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recorder', full_name='ml_assignment_proto.Features.recorder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recording_time', full_name='ml_assignment_proto.Features.recording_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='ml_assignment_proto.Features.features', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=416,
)

_FEATURES.fields_by_name['user'].message_type = ml__assignment__proto_dot_user__pb2._USER
_FEATURES.fields_by_name['recorder'].message_type = ml__assignment__proto_dot_recording__device__pb2._RECORDINGDEVICE
_FEATURES.fields_by_name['recording_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FEATURES.fields_by_name['features'].message_type = _FEATURE
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(
  DESCRIPTOR = _FEATURE,
  __module__ = 'ml_assignment_proto.features_pb2'
  # @@protoc_insertion_point(class_scope:ml_assignment_proto.Feature)
  ))
_sym_db.RegisterMessage(Feature)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), dict(
  DESCRIPTOR = _FEATURES,
  __module__ = 'ml_assignment_proto.features_pb2'
  # @@protoc_insertion_point(class_scope:ml_assignment_proto.Features)
  ))
_sym_db.RegisterMessage(Features)


# @@protoc_insertion_point(module_scope)
